import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <header className="sticky top-0 z-40 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
                    <div className="container flex h-14 items-center">
                        <Link className="flex items-center justify-center px-4" href="/">
                            <span className="sr-only">Luis Thieme</span>
                            <span className="font-bold text-xl">Luis Thieme</span>
                        </Link>
                        <nav className="ml-auto flex gap-4 sm:gap-6">
                            <Link className="text-sm font-medium hover:underline underline-offset-4" href="/#projects">
                                Skills
                            </Link>
                            <Link className="text-sm font-medium hover:underline underline-offset-4" href="/#skills">
                                Technologies
                            </Link>
                            <Link className="text-sm font-medium hover:underline underline-offset-4" href="/#contact">
                                Contact
                            </Link>
                        </nav>
                    </div>
                </header>
                {children}
            </body>
        </html>
    );
}
